apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarantine-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarantine-controller
  template:
    metadata:
      labels:
        app: quarantine-controller
    spec:
      serviceAccountName: quarantine-controller
      containers:
        - name: controller
          image: xxradar/quarantine-controller:latest
          env:
            - name: KOPF_LOGLEVEL
              value: DEBUG
