apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarantine-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarantine-controller
  template:
    metadata:
      labels:
        app: quarantine-controller
    spec:
      serviceAccountName: quarantine-controller
      containers:
        - name: controller
          image: xxradar/quarantine-controller:latest
          # Remove 'command' and 'args' unless you need to override them
          # If you need to pass additional arguments, you can use 'args'
          # command: ["python"]
          # args:
          #   - "quarantine_controller.py"
          #   - "--cluster-wide"
          env:
            - name: KOPF_LOGLEVEL
              value: DEBUG
