apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: quarantines.quarantine.example.com
spec:
  group: quarantine.example.com
  names:
    kind: Quarantine
    listKind: QuarantineList
    plural: quarantines
    singular: quarantine
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              deploymentName:
                type: string
              namespace:
                type: string
